
// app/layout.tsx
import './globals.css'
import type { Metadata } from 'next'
import { headers } from 'next/headers'

import { cookieToInitialState } from 'wagmi'
import { config } from '../app/config'
import Web3ModalProvider from '../context/web3modal'
import Sidebar from '@/components/sidebar'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  const initialState = cookieToInitialState(config, headers().get('cookie'))
  return (
    <html lang="en">
      <body className='bg-black text-white p-6'>
        
        <Web3ModalProvider initialState={initialState}>
        <Sidebar></Sidebar>
          <div className='ml-[20rem] p-8 pt-0'>
            {children}
          </div>  
        </Web3ModalProvider>
      </body>
    </html>
  )
}